#!/bin/sh

set -e

# Link prefpane
if [ -L "/Library/PreferencePanes/${applicationName}.prefPane" ]; then
	rm "/Library/PreferencePanes/${applicationName}.prefPane"
fi

ln -s "${installName}/Contents/Resources/${applicationName}.prefPane" "/Library/PreferencePanes"

# copy default launchd file and start daemon
/usr/bin/ditto "${installName}/Contents/Resources/${applicationName}.prefPane/Contents/Resources/service.plist" "/Library/LaunchDaemons/${serviceName}.plist"
/bin/launchctl load "/Library/LaunchDaemons/${serviceName}.plist"

# if there is a setup or something else to be started, do so now
JAVAEXECUTABLE=`find "${installName}/Contents" -name "java" -type f`
RUNAFTER_MAINJAR="${runAfterMainJar}"
RUNAFTER_MAINCLASS="${runAfterMainClass}"
RUNAFTER_WORKINGDIR="${runAfterWorkingDir}"

# this is to be inteded with an embedded JRE and existing jars only
if [ ! -z "$JAVAEXECUTABLE" ] && [ ! -z "$RUNAFTER_MAINJAR" ]; then
	
	if [ -z "$RUNAFTER_WORKINGDIR" ]; then
		RUNAFTER_WORKINGDIR="${installName}/Contents/Java"
	fi
	
	if [ -z "$RUNAFTER_MAINCLASS" ]; then
		$(cd "$RUNAFTER_WORKINGDIR" && "$JAVAEXECUTABLE" -jar "$RUNAFTER_MAINJAR" )&
	else
		$(cd "$RUNAFTER_WORKINGDIR" && "$JAVAEXECUTABLE" -classpath "$RUNAFTER_MAINJAR" "$RUNAFTER_MAINCLASS" )&
	fi
fi
